#!/bin/sh
set -x 
docker run \
       -v $PWD:/data:ro \
       -v $PWD/../result:/result \
       -v $PWD/../cache:/var/cache/apt/archives \
       -v $PWD/`dirname $0`:/buildscripts:ro \
       -ti eos-dev-buildbox \
       sh /buildscripts/buildscript.sh
#
